/**
 * key.ts — wallet-signed Orbio key derivation and `GET /key` balance reading (S-03, AC4/AC5,
 * tasks/S-03.md). `deriveOrbioKey()` is exercised with a throwaway private key generated by
 * viem's `generatePrivateKey()` — never a real key, never printed (AC4's ticket instruction:
 * "generate a throwaway key ... and never print it" — this file only ever asserts on the
 * *derived key string*, never logs the private key itself, including on test failure since
 * vitest's default assertion output never touches `pk`).
 */
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { describe, expect, it, vi } from 'vitest';
import { redact } from '../redact.js';
import { AdapterShapeError, GatewayKeyHttpError } from './errors.js';
import {
  deriveOrbioKey,
  orbioKeyDerivationMessage,
  parseOrbioBalanceHeader,
  readApiBalance,
} from './key.js';

describe('orbioKeyDerivationMessage', () => {
  it('is exactly "Orbio API key · chain 4663 · epoch <n>" with U+00B7 middle dots, not hyphens', () => {
    const msg = orbioKeyDerivationMessage(0);
    expect(msg).toBe('Orbio API key · chain 4663 · epoch 0');
    // Guard against a copy-paste substitution to a visually similar character (bullet U+2022,
    // hyphen, or a plain ASCII period) — the gateway's own derivation must match byte-for-byte.
    expect(msg.includes('·')).toBe(true);
    expect(msg).not.toContain('•');
  });

  it('interpolates the epoch', () => {
    expect(orbioKeyDerivationMessage(3)).toBe('Orbio API key · chain 4663 · epoch 3');
  });
});

describe('deriveOrbioKey — determinism (AC4)', () => {
  it('the same throwaway private key + epoch always derives the same key', async () => {
    const pk = generatePrivateKey(); // never logged, never asserted on directly
    const key1 = await deriveOrbioKey(pk, 0);
    const key2 = await deriveOrbioKey(pk, 0);
    expect(key1).toBe(key2);
  });

  it('a different epoch derives a different key for the same private key', async () => {
    const pk = generatePrivateKey();
    const key0 = await deriveOrbioKey(pk, 0);
    const key1 = await deriveOrbioKey(pk, 1);
    expect(key0).not.toBe(key1);
  });

  it('a different private key derives a different key for the same epoch', async () => {
    const keyA = await deriveOrbioKey(generatePrivateKey(), 0);
    const keyB = await deriveOrbioKey(generatePrivateKey(), 0);
    expect(keyA).not.toBe(keyB);
  });

  it('has the sk-orb-<epoch>-<base64> shape and decodes to a 65-byte signature', async () => {
    const pk = generatePrivateKey();
    const key = await deriveOrbioKey(pk, 0);
    const match = /^sk-orb-0-([A-Za-z0-9+/=]+)$/.exec(key);
    expect(match).not.toBeNull();
    const body = match?.[1] as string;
    const bytes = Buffer.from(body, 'base64');
    expect(bytes.byteLength).toBe(65); // r (32) + s (32) + v (1), EIP-191 personal_sign
  });

  it("the derived key's address matches privateKeyToAccount's (sanity: signing the right key)", async () => {
    const pk = generatePrivateKey();
    const account = privateKeyToAccount(pk);
    // Not asserted against the key body directly (that's the signature) — just documents that
    // deriveOrbioKey() is signing with the account this pk actually controls, via a second,
    // independent verification path: recovering the signer from the raw signature bytes.
    const key = await deriveOrbioKey(pk, 0);
    const body = /^sk-orb-0-([A-Za-z0-9+/=]+)$/.exec(key)?.[1] as string;
    const sigBytes = Buffer.from(body, 'base64');
    const sigHex = `0x${sigBytes.toString('hex')}` as const;
    const { verifyMessage } = await import('viem');
    const valid = await verifyMessage({
      address: account.address,
      message: orbioKeyDerivationMessage(0),
      signature: sigHex,
    });
    expect(valid).toBe(true);
  });
});

describe('readApiBalance', () => {
  it('parses balance.available/used from a 2xx response (PRD §3 shape)', async () => {
    const fetchImpl = vi.fn(
      async () =>
        new Response(
          JSON.stringify({
            balance: { currency: 'USD', available: '12.340000', used: '0.660000' },
            rate_limit: { requests_per_minute: 120, concurrent: 32 },
          }),
          { status: 200 },
        ),
    );
    const result = await readApiBalance('https://api.example/v1', 'sk-orb-0-abc', fetchImpl);
    expect(result).toEqual({ available: '12.340000', used: '0.660000' });
    expect(fetchImpl).toHaveBeenCalledWith(
      'https://api.example/v1/key',
      expect.objectContaining({ headers: { Authorization: 'Bearer sk-orb-0-abc' } }),
    );
  });

  it('throws GatewayKeyHttpError with a redacted body on a non-2xx status (401 "unknown key", AC4)', async () => {
    // The exact live shape recorded 2026-09-19 (docs/api-notes.md "S-03 chain reads") for a
    // throwaway wallet-derived key that has never been activated — acceptable AC4 evidence per
    // the ticket ("a 401 whose message says the key is unknown ... acceptable").
    const fetchImpl = vi.fn(
      async () =>
        new Response(
          JSON.stringify({
            error: {
              message: 'This Orbio API key is unknown or has been revoked.',
              type: 'invalid_request_error',
              code: 'invalid_api_key',
              param: null,
            },
          }),
          { status: 401 },
        ),
    );
    let error: unknown;
    try {
      await readApiBalance('https://api.example/v1', 'sk-orb-0-throwaway', fetchImpl);
    } catch (e) {
      error = e;
    }
    expect(error).toBeInstanceOf(GatewayKeyHttpError);
    expect((error as GatewayKeyHttpError).status).toBe(401);
    const body = (error as GatewayKeyHttpError).redactedBody as { error: { message: string } };
    expect(body.error.message).toContain('unknown or has been revoked');
  });

  it('a 401 "malformed key" is distinguishable from "unknown key" (AC4: the ticket treats them differently)', async () => {
    const fetchImpl = vi.fn(
      async () =>
        new Response(JSON.stringify({ error: { message: 'malformed api key' } }), { status: 401 }),
    );
    let error: unknown;
    try {
      await readApiBalance('https://api.example/v1', 'not-even-key-shaped', fetchImpl);
    } catch (e) {
      error = e;
    }
    expect(error).toBeInstanceOf(GatewayKeyHttpError);
    const body = (error as GatewayKeyHttpError).redactedBody as { error: { message: string } };
    expect(body.error.message).toBe('malformed api key');
  });

  it('throws AdapterShapeError on a 2xx body missing balance.available/used (CLAUDE.md #6)', async () => {
    const fetchImpl = vi.fn(
      async () => new Response(JSON.stringify({ balance: { currency: 'USD' } }), { status: 200 }),
    );
    let error: unknown;
    try {
      await readApiBalance('https://api.example/v1', 'sk-orb-0-abc', fetchImpl);
    } catch (e) {
      error = e;
    }
    expect(error).toBeInstanceOf(AdapterShapeError);
    expect((error as AdapterShapeError).source).toBe('gateway_key');
  });

  it('throws AdapterShapeError (not GatewayKeyHttpError) on a 2xx non-JSON body', async () => {
    const fetchImpl = vi.fn(async () => new Response('<html>not json</html>', { status: 200 }));
    let error: unknown;
    try {
      await readApiBalance('https://api.example/v1', 'sk-orb-0-abc', fetchImpl);
    } catch (e) {
      error = e;
    }
    expect(error).toBeInstanceOf(AdapterShapeError);
  });

  it('never includes the key itself in a thrown error (redact() would catch it anyway, but the code never even tries)', async () => {
    const key = 'sk-orb-0-SECRETSECRETSECRETSECRET==';
    const fetchImpl = vi.fn(async () => new Response('not json', { status: 500 }));
    let error: unknown;
    try {
      await readApiBalance('https://api.example/v1', key, fetchImpl);
    } catch (e) {
      error = e;
    }
    expect(JSON.stringify(redact(error))).not.toContain('SECRETSECRETSECRETSECRET');
  });
});

describe('parseOrbioBalanceHeader', () => {
  it('parses a plain decimal string', () => {
    expect(parseOrbioBalanceHeader('12.34')).toBe('12.34');
    expect(parseOrbioBalanceHeader('0')).toBe('0');
    expect(parseOrbioBalanceHeader('-1.5')).toBe('-1.5');
  });

  it('returns null for absent/empty/non-decimal values, never throws', () => {
    expect(parseOrbioBalanceHeader(null)).toBeNull();
    expect(parseOrbioBalanceHeader(undefined)).toBeNull();
    expect(parseOrbioBalanceHeader('')).toBeNull();
    expect(parseOrbioBalanceHeader('not-a-number')).toBeNull();
  });
});
