-- S-02 (Sprint 1.0, PRD docs/PRD-1.0-sprint.md §4 T-2, §6) — hand-written delta migration.
--
-- Unlike 001-004, this file is NOT regenerated by gen-sql.ts: gen-sql always renders the FULL
-- target schema (every `create table if not exists ...` for every table in schema.ts), which is
-- exactly right for a fresh project or a fresh SQLite file, but is a no-op against an
-- already-migrated Postgres database — `create table if not exists` does not add a column to a
-- table that already exists, and 001-004 have already run once on the real Supabase project
-- (T-002, 2026-09-09). This file carries forward only the DELTA those already-applied files
-- cannot: the new `requested_model` / `route_reason` / `baseline_cost_usd` / `caller_key_id`
-- columns on `usage_events`, and the three new tables (`caller_keys`, `treasury_events`,
-- `chain_snapshots`) with their RLS and append-only/guard triggers.
--
-- Every statement here is written to be safely re-run (AC7: "applies twice without error") using
-- `if not exists` for tables/columns/indexes, `create or replace function` for trigger bodies,
-- and `drop ... if exists` immediately before `create` for policies/triggers, which Postgres has
-- no native `if not exists` form for. Column definitions, RLS policy shape (`via-agent-public` /
-- `none`) and trigger bodies below are hand-copied from what `pnpm --filter @orbio-treasurer/core
-- gen:sql` produces for these same tables in 001_schema.sql/002_rls.sql/003_append_only.sql (the
-- audit focus "migration parity with gen-sql output") — schema.ts stays the single source of
-- truth for the column list itself; do not let this file's copy drift from it.

-- --- usage_events: new nullable metering columns (S-02 In scope) ----------------------------
alter table usage_events add column if not exists requested_model text;
alter table usage_events add column if not exists route_reason text;
alter table usage_events add column if not exists baseline_cost_usd numeric(18,6);
-- caller_keys must exist before this FK is added — created below, but Postgres resolves FK
-- targets at constraint-creation time, so caller_keys is created first regardless of file order.

-- --- caller_keys ------------------------------------------------------------------------------
create table if not exists caller_keys (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references agents(id),
  key_hash text not null unique,
  key_prefix text not null,
  label text,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

alter table usage_events add column if not exists caller_key_id uuid references caller_keys(id);

-- --- treasury_events (append-only) --------------------------------------------------------------
create table if not exists treasury_events (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references agents(id),
  at timestamptz not null,
  kind text not null check (kind in ('settle','claim','activate','buy','stake','mode_change','alert','dry_run')),
  amount numeric(30,0),
  token text check (token in ('CREDIT','ORBIO','USDG','ETH')),
  usd_value numeric(18,6),
  tx_hash text,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_treasury_events_agent_id_at_desc on treasury_events (agent_id, at desc);

-- --- chain_snapshots (append-only) --------------------------------------------------------------
create table if not exists chain_snapshots (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid not null references agents(id),
  as_of timestamptz not null,
  staked_orbio numeric(30,0),
  settled_credit numeric(30,0),
  credit_wallet numeric(30,0),
  credit_api_available numeric(18,6),
  credit_api_used numeric(18,6),
  quote_credit_per_usdg numeric(18,6),
  eth_balance numeric(30,0),
  usdg_balance numeric(30,0),
  mode text,
  rpc_url_host text,
  created_at timestamptz not null default now()
);
create index if not exists idx_chain_snapshots_agent_id_as_of_desc on chain_snapshots (agent_id, as_of desc);

-- --- RLS (002_rls.sql pattern: anon SELECT where the row's agent is public; caller_keys is
--     'none', same as key_meta — key material metadata is never public) -----------------------
alter table caller_keys enable row level security;
-- caller_keys: no anon policy — anon has no read access (RLS default-denies), same as key_meta.

alter table treasury_events enable row level security;
drop policy if exists treasury_events_anon_select on treasury_events;
create policy treasury_events_anon_select on treasury_events for select to anon using (
  exists (select 1 from agents a where a.id = treasury_events.agent_id and a.public = true)
);
grant select on treasury_events to anon;

alter table chain_snapshots enable row level security;
drop policy if exists chain_snapshots_anon_select on chain_snapshots;
create policy chain_snapshots_anon_select on chain_snapshots for select to anon using (
  exists (select 1 from agents a where a.id = chain_snapshots.agent_id and a.public = true)
);
grant select on chain_snapshots to anon;

-- --- Triggers (003_append_only.sql pattern) ----------------------------------------------------
-- ledger_reject_write() already exists (003_append_only.sql, applied before this migration in
-- every real deployment); `create or replace` here only guards a from-scratch apply order.
create or replace function ledger_reject_write() returns trigger as $$
begin
  raise exception '% is append-only: % is not permitted', TG_TABLE_NAME, TG_OP;
end;
$$ language plpgsql;

-- caller_keys: mutable-guard — only `revoked_at` may ever change (schema.ts writePolicy). The
-- null -> value-once semantics of revocation itself (AC3: "a second call throws") is enforced by
-- LedgerStore.revokeCallerKey at the application boundary (packages/core/src/ledger/{sqlite,postgres}/store.ts),
-- not by this trigger — this trigger only stops a caller from changing any OTHER column, exactly
-- mirroring the agents_guard_write / orders_guard_write pattern gen-sql.ts already generates.
create or replace function caller_keys_guard_write() returns trigger as $$
begin
  if TG_OP = 'DELETE' then
    raise exception 'caller_keys rows cannot be deleted';
  end if;
  if TG_OP = 'UPDATE' then
    if NEW.id IS DISTINCT FROM OLD.id
       OR NEW.agent_id IS DISTINCT FROM OLD.agent_id
       OR NEW.key_hash IS DISTINCT FROM OLD.key_hash
       OR NEW.key_prefix IS DISTINCT FROM OLD.key_prefix
       OR NEW.label IS DISTINCT FROM OLD.label
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
    then
      raise exception 'caller_keys: only revoked_at may be updated';
    end if;
  end if;
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trg_caller_keys_guard on caller_keys;
create trigger trg_caller_keys_guard
before update or delete on caller_keys
for each row execute function caller_keys_guard_write();

drop trigger if exists trg_treasury_events_append_only on treasury_events;
create trigger trg_treasury_events_append_only
before update or delete on treasury_events
for each row execute function ledger_reject_write();

drop trigger if exists trg_chain_snapshots_append_only on chain_snapshots;
create trigger trg_chain_snapshots_append_only
before update or delete on chain_snapshots
for each row execute function ledger_reject_write();
